# .gitlab-ci.yml
# Author: //coding.lifestyle Studio
# License: MIT License
# Repository: https://github.com/lcwiek/PortKnocker.ps1

stages:
  - test

variables:
  SCRIPT_NAME: "PortKnocker.ps1"
  
test_script:
  stage: test
  image: mcr.microsoft.com/powershell
  script:
    - pwsh -File addon/syntax-check.ps1 -ScriptPath $SCRIPT_NAME

