stages:
  - test

variables:
  SCRIPT_NAME: "PortKnocker.ps1"
  
test_script:
  stage: test
  image: mcr.microsoft.com/powershell
  script:
    - pwsh -File syntax-check.ps1 -ScriptPath PortKnocker.ps1

